name: Secure CI/CD Pipeline

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Dependency Scan (pip-audit)
        run: |
          pip install pip-audit
          pip-audit --severity high

      - name: SAST Scan (Semgrep)
        uses: returntocorp/semgrep-action@v1

      - name: Build Docker image
        run: docker build -t project1:ci .

      - name: Container Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: project1:ci
          severity: CRITICAL,HIGH
          exit-code: 1
